# include <stdio.h>
# include <stdlib.h>
# include <string.h>

/*  Generate external Gaussian input file to calculate force and single point energy, and Hessian.  */

int main(int argc, const char *const argv[])
{
  const double BohrToAngstrom = 0.5291773;
  char line[BUFSIZ] = "";
  char gauLevel[BUFSIZ] = "";
  char gauParallel[BUFSIZ] = "";
  char gauMemory[BUFSIZ] = "";
  FILE * iflp = NULL;
  FILE * oflp1 = NULL;  /*  for Gaussian  */
  FILE * oflp2 = NULL;  /*  for dftd4  */
  unsigned int natoms = 0;
  int charge = 0;
  unsigned int multiplicity = 0;
  unsigned int i = 0;
  unsigned int atomIndex = 0;
  double atomXCoor = 0.;
  double atomYCoor = 0.;
  double atomZCoor = 0.;
  unsigned int needDeri = 0;
  const char *AtomNameList[] = {"", 
     "H" , "He", "Li", "Be", "B" , "C" , "N" , "O" ,
     "F" , "Ne", "Na", "Mg", "Al", "Si", "P" , "S" ,
     "Cl", "Ar", "K" , "Ca", "Sc", "Ti", "V" , "Cr",
     "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Ga", "Ge",
     "As", "Se", "Br", "Kr", "Rb", "Sr", "Y" , "Zr",
     "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag", "Cd",
     "In", "Sn", "Sb", "Te", "I" , "Xe", "Cs", "Ba",
     "La", "Ce", "Pr", "Nd", "Pm", "Sm", "Eu", "Gd",
     "Tb", "Dy", "Ho", "Er", "Tm", "Yb", "Lu", "Hf",
     "Ta", "W" , "Re", "Os", "Ir", "Pt", "Au", "Hg",
     "Tl", "Pb", "Bi", "Po", "At", "Rn", "Fr", "Ra",
     "Ac", "Th", "Pa", "U" , "Np", "Pu", "Am", "Cm",
     "Bk", "Cf", "Es", "Fm", "Md", "No", "Lr", "Rf",
     "Db", "Sg", "Bh", "Hs", "Mt", "Ds", "Rg", "Cn"};

  /*  acquire Gaussian level from ExtDFTD4_settings.ini  */
  iflp = fopen("ExtDFTD4_settings.ini", "r");
  while (! feof(iflp))
  {
    fgets(line, BUFSIZ, iflp);
    if (strstr(line, "the level without dispersion correction in Gaussian"))
    {
      fgets(line, BUFSIZ, iflp);
      while (line[strlen(line) - 1] == '\r' || line[strlen(line) - 1] == '\n')
        line[strlen(line) - 1] = '\0';
      strcpy(gauLevel, line);
      break;
    }
  }
  fseek(iflp, 0, SEEK_SET);
  while (! feof(iflp))
  {
    fgets(line, BUFSIZ, iflp);
    if (strstr(line, "the Gaussian parallel setting"))
    {
      fgets(line, BUFSIZ, iflp);
      while (line[strlen(line) - 1] == '\r' || line[strlen(line) - 1] == '\n')
        line[strlen(line) - 1] = '\0';
      strcpy(gauParallel, line);
      break;
    }
  }
  fseek(iflp, 0, SEEK_SET);
  while (! feof(iflp))
  {
    fgets(line, BUFSIZ, iflp);
    if (strstr(line, "the Gaussian memory setting"))
    {
      fgets(line, BUFSIZ, iflp);
      while (line[strlen(line) - 1] == '\r' || line[strlen(line) - 1] == '\n')
        line[strlen(line) - 1] = '\0';
      strcpy(gauMemory, line);
      break;
    }
  }
  fclose(iflp);
  iflp = NULL;

  /*  Generate Gaussian and dftd4 Input Files  */
  iflp = fopen(argv[1], "r");
  oflp1 = fopen("useExtGau.gjf", "w");
  oflp2 = fopen("useExtDFTD4.xyz", "w");
  fgets(line, BUFSIZ, iflp);
  sscanf(line, "%u %u %d %u", & natoms, & needDeri, & charge, & multiplicity);
  fprintf(oflp1, "%s\n", gauParallel);
  fprintf(oflp1, "%s\n", gauMemory);
  fprintf(oflp1, "%s", "%chk=useExtGau.chk\n");
  fprintf(oflp1, "# ");
  fprintf(oflp2, "%u\nGenerated by GeneExtInp\n", natoms);
  if (needDeri == 0)
    ;
  else if (needDeri == 1)
    fprintf(oflp1, "Force ");
  else if (needDeri == 2)
    fprintf(oflp1, "Freq IOp(7/33=1) ");
  fprintf(oflp1, "%s\n", gauLevel);
  fprintf(oflp1, "\nGenerated by GeneExtInp\n\n%d %u\n", charge, multiplicity);
  for (i = 1; i <= natoms; i ++)
  {
    fgets(line, BUFSIZ, iflp);
    sscanf(line, "%u %lf %lf %lf", & atomIndex, & atomXCoor, & atomYCoor, & atomZCoor);
    /*  read in unit Bohr  */
    atomXCoor *= BohrToAngstrom;
    atomYCoor *= BohrToAngstrom;
    atomZCoor *= BohrToAngstrom;
    fprintf(oflp1, " %-2s               %12.8lf  %12.8lf  %12.8lf\n", AtomNameList[atomIndex], \
            atomXCoor, atomYCoor, atomZCoor);
    fprintf(oflp2, " %-2s               %12.8lf  %12.8lf  %12.8lf\n", AtomNameList[atomIndex], \
            atomXCoor, atomYCoor, atomZCoor);
  }
  fprintf(oflp1, "\n");
  fprintf(oflp2, "\n");
  fclose(iflp);
  fclose(oflp1);
  fclose(oflp2);
  iflp = NULL;
  oflp1 = NULL;
  oflp2 = NULL;

  return 0;
}

